### ISSUE TITLE
BaudOther(9600) fails where Baud9600 succeeds

### ISSUE THREAD

**Issue by Susurrus** [dcuddeback/serial-rs#10]
I have a program I'm working on where I'd like to specify the baud rate from the command line. I'm using the `BaudOther` enum. I'm using an FTDI cable and if I use `Baud9600` I can configure it properly but if I use `BaudOther(9600)` it fails. I'm not certain how to debug this further.

**Comment by dcuddeback** [comment]
@Susurrus I do need to improve the support for non-standard baud rates with `BaudOther`. In this case, if you're only using fairly standard baud rates, it would be pretty simple to write a function to convert an integer baud rate to the appropriate `BaudRate` enum variant. I think that would be a useful thing to add to this crate. I'll add something for this in the next release.

**Comment by Susurrus** [comment]
That functionality is the whole point of `BaudOther()` I think already so I don't think there's a need for an additional function; I think there's a need for `BaudOther()` to work correctly. I'd be happy to chip in here and make or test changes with my hardware, but I don't really know where to start. If you can point me in the right directly maybe I could get `BaudOther()` to work right.

**Comment by dcuddeback** [comment]
@Susurrus I believe there's a misunderstanding about the intended purpose of `BaudOther`. `Baud9600`, `Baud1200`, etc. are standard baud rates that are well-supported across many platforms. Using them should be fairly reliable. `BaudOther`, on the other hand, is provided to access non-standard baud rates (rates that don't have a specific `BaudRate` enum variant). Non-standard baud rates are system-specific, and so they are less portable and may not always work. Because of that, `BaudOther` is not guaranteed to work with all baud rates.

If you want to use 9600 baud rate, you really should use the `Baud9600` enum variant. The method I'm proposing adding would make enum selection transparent to the user of the library. I'd prefer that, because it encourages correct usage, which increases portability. I should have time to work on it later this week, and I'll try to make the documentation clearer, too.

**Comment by Susurrus** [comment]
So if I understand you correctly you'd get rid of the enum completely and switch to using a function that takes in an arbitrary integer instead? I think that would be very beneficial.

**Comment by Susurrus** [comment]
Have you been able to use BaudOther() successfully? I'm not certain it works. I have two FTDI cables connected together that I can open and operate successfully at 921600 baud. I can't configure them properly with this library for that baud rate. So currently 9600 and 921600 don't work with `BaudOther`. Looking at https://github.com/dcuddeback/serial-rs/blob/master/src/posix/tty.rs#L367 it does look like a library error rather than an actual hardware error as there are many more values exposed by the OS-specific enum in termios (https://github.com/dcuddeback/termios-rs/blob/master/src/os/linux.rs#L131).

I'm not sure the best way to write the backend code, but I don't think the best interface for me, as a user of the serial.rs library, is to expose an enum interface for baud rates. They can be any value for a lot of different hardware, and exposing them as enums in the serial.rs API just makes them harder to use since the values are already numbers. I think they only interface should be using a `u32` that is them mapped to the proper termios baud rates entirely in the backend. It should be much cleaner for me, the user of this library to do `settings.set_baud_rate(921600);` than wrapping things in `BaudOther()`.

**Comment by dcuddeback** [comment]
@Susurrus Did you try any of the seven baud rates that have match patterns using `BaudOther` in the method that you linked to above? I'd be interested to hear if one of them doesn't work for you. Obviously, any baud rates that aren't implemented there aren't going to work. If OS-specific baud rates (such as 921600 in Linux) is something you need, I can add those pretty easily.

Did you look at the referenced commit? It adds a function to get an appropriate `BaudRate` variant from an integer. There are several benefits to using an enum over plain integers, so I'm not planning on replacing the `BaudRate` enum. I explained the portability benefits above and clarified them in the documentation as well. Enums enable more errors to be caught at compile time and give the compiler freedom to optimize. The underlying OS interfaces use symbolic constants, so even if you were using C, you wouldn't be able to treat baud rates as just a number. The `BaudRate::from_speed` function (added in the commit referenced earlier in this thread) does what you're asking without discarding the benefits of using an enum.

**Comment by Susurrus** [comment]
Yes, I tried the 230400 baud rate, and that works fine.

I've tested your feature/integer-baud-rates branch, and it works for me. I did want to suggest you use the Into or From iterators for `uint16` and `str` for BaudRate, instead of adding another function. Then you can just pass an integer or string directly into `set_baud_rate` and this extra function call wouldn't need to be called explicitly. 

As to your second comment, you can still get compile-time errors even when using integers for constants, and for non-constants it can't be done anyways. With these changes you now have 3 interfaces to baud rates: this function that takes integers, specific baud rate enums, and then an enum for non-standard baud rates. The problem with this is that these are somewhat redundant between them, but the code doesn't support one of those code paths so things like `baudOther(9600)` fails which is surprising to the user. This is why I suggest only exposing integers in this library's API. There's a single, clear way to set the baud rates instead of 3 almost-equivalent ways. This follows from the Principle of Least Surprise and Python's One Right Way approach to things.

**Comment by dcuddeback** [comment]
@Susurrus 

> Yes, I tried the 230400 baud rate, and that works fine.

Great. Thanks for confirming.

> I've tested your feature/integer-baud-rates branch, and it works for me.

Sounds good. I'll go with that then. I don't want to complicate the API by adding multiple ways to set a serial port's baud rate. The current API provides a single, type-safe way to set the baud rate, and the new constructor makes it easy to convert numeric baud rates to the right enum. Anything else (like parsing strings) is application-specific. Let's agree to disagree about what's the least surprising interface.
