### ISSUE TITLE
Document how to close a serial port

### ISSUE THREAD

**Issue by Susurrus** [dcuddeback/serial-rs#15]
There isn't a `close()` function and calling `port.drop()` isn't possible. I'm unclear if calling `open()` multiple times when it succeeds will keep the initial ports open or they will be closed automatically. If so, then this should be explicitly documented, otherwise a `close()` method should be added.

**Comment by dcuddeback** [comment]
@Susurrus Serial ports follow the RAII pattern. The port will be closed when it goes out of scope (using the `Drop` trait). I'll make this more clear in the documentation.
