### ISSUE TITLE
Question: Raise RTS/DSR lines without handshaking

### ISSUE THREAD

**Issue by valarauca** [dcuddeback/serial-rs#20]
Is it possible to raise both the RTS and DSR lines independent of handshaking?

I need these lines to be high for a serial to TTL converter but my communication will be bi-directional while this is taking place.

**Comment by dcuddeback** [comment]
You can assert RTS and DTR at any time after opening a serial port. DSR is read-only.

I'm not sure what you mean about being independent of handshaking. There's nothing specific to handshaking in serial-rs's code. It just asserts the lines when asked. The meaning of the lines depends on what they're hooked up to. It's common to use these lines as GPIO for simple tasks that don't involve handshaking.

I encourage you to give it a try and see if it works for your use case.

**Comment by valarauca** [comment]
So I've gone ahead and hacked together a rough implementation of what I'm looking for. Code located [on playpen](https://play.rust-lang.org/?gist=f8adcfbabea6885d91baa642b769c89a&version=stable&backtrace=0) and [on github](https://gist.github.com/anonymous/f8adcfbabea6885d91baa642b769c89a). Excuse my mess.

When ran on my machine line 53 fails. The description I receive is `The parameter is incorrect`

I then attempt to fetch the OS error by calling `::std::io::Error::last_os_error()` See Line 58. But my OS error value is 0, and I get the message `The operation completed successfully`.

So I'm attempting to get cause/description but I believe [the `serial::Error`](https://dcuddeback.github.io/serial-rs/serial/struct.Error.html) is out of date? because when I attempt to call `::serial::Error::description()` I'm told it doesn't exist, and the trait `Stderr` redirects to `::io::Error`. 

I'm trying to pull the OS-Error code so I can look up what's going wrong.

Rust Compiler: 1.8.0 (db2939409) GNU ABI WIndows 7 x64 professional

Cargo:  0.9.0-Nightly (8fc3fd8)

**Comment by valarauca** [comment]
Submitted a [PR](https://github.com/dcuddeback/serial-rs/pull/23) to assist in debugging this issue.

**Comment by dcuddeback** [comment]
Your example works fine for me with an FT232R on both OS X and Windows.

Line 53 failing means that [`EscapeCommFunction()`](https://msdn.microsoft.com/en-us/library/windows/desktop/aa363254%28v=vs.85%29.aspx) resulted in an error. "The parameter is incorrect" is the error message from the OS after calling `EscapeCommFunction()`. Maybe your hardware or driver doesn't support setting DTR? Does it work with the equivalent C code or under a different OS?

Calling `::std::io::Error::last_os_error()` probably won't help you, because the error code has already been consumed to produce the `serial::Error`.

The documentation is correct. You just have to have the `std::error::Error` trait in scope. I'm surprised the compiler error message didn't mention that for you. The description is going to be the same that you already saw: "The parameter is incorrect."

Adding the OS code to `serial::Error` won't give you any more information. It's just a numeric version of the error message: "The parameter is incorrect."

**Comment by valarauca** [comment]
[This summarizes ](https://stackoverflow.com/questions/37307559/windows-error-87-when-raising-dtr-line-serial)my debug efforts so far. I'll just call out a couple things.

> Calling `::std::io::Error::last_os_error()` probably won't help you, because the error code has already been consumed to produce the `serial::Error.`

Found out the hard way. That's why I submitted a pull request.

> Does it work with the equivalent C code or under a different OS?

Raising DTR works in Python3.5 via PySerial Library (on same computer) with same USB/RS232 convert/emulator thing.

I'm actually working in enterprise so getting this working under OSX/Linux won't fly.

> Adding the OS code to `serial::Error` won't give you any more information. It's just a numeric version of the error message: "The parameter is incorrect."

True, But I wanted to confirm the code.

:.:.:

I'm gonna go ahead and play with a different serial converter to see if it makes a difference (all mine are the same model). Thanks for the help

**Comment by dcuddeback** [comment]
> Raising DTR works in Python3.5 via PySerial Library (on same computer) with same USB/RS232 convert/emulator thing.

That's something. Maybe there's something different about the way PySerial and serial-rs call the Windows API functions. It'd be helpful to reduce this to a minimal C program that shows the difference, since that's the common denominator between the two libraries. I could try to look into this if I can reproduce the issue. Which USB/RS232 converter are you using?

**Comment by dcuddeback** [comment]
@valarauca In your original StackOverflow question (https://stackoverflow.com/questions/37284228/disable-rts-dsr-handshaking-while-keeping-lines-high-in-pyserial), you're setting `dsrdtr` in the constructor, which makes PySerial set the `fDtrControl` flag of `DCB` to `DTR_CONTROL_HANDSHAKE`: https://github.com/pyserial/pyserial/blob/9d893054aae0229aea504337c34ff9c7138953d9/serial/serialwin32.py#L206. Here's what the documentation says about `DTR_CONTROL_HANDSHAKE` (https://msdn.microsoft.com/en-us/library/windows/desktop/aa363214(v=vs.85).aspx):

> Enables DTR handshaking. If handshaking is enabled, it is an error for the application to adjust the line by using the EscapeCommFunction function.

That sounds like the issue you're having, and it makes sense that the field would be set after using PySerial, but I haven't had any luck replicating it with the FT232R. I don't set that anywhere in `serial-rs`. I should update `serial-rs` to set the desired value for all the fields in the `DCB` struct.

Kinda off topic, but to get the equivalent functionality of `serial-rs` with PySerial, I think you'd want to use the `dtr` setter (https://github.com/pyserial/pyserial/blob/9d893054aae0229aea504337c34ff9c7138953d9/serial/serialutil.py#L396) which uses `EscapeCommFunction` (https://github.com/pyserial/pyserial/blob/9d893054aae0229aea504337c34ff9c7138953d9/serial/serialwin32.py#L363) to set the DTR line without enabling `DTR_CONTROL_HANDSHAKE`.

**Comment by dcuddeback** [comment]
@valarauca I haven't reproduced it exactly, but with some changes I was able to get the same error message for the RTS line. Would you mind trying my `bugfix/issue-20` branch to see if it solves your problem? It sets all of the flag bits in the `DCB` structure. https://github.com/dcuddeback/serial-rs/compare/bugfix/issue-20

**Comment by valarauca** [comment]
After doing a lot of digging in the windows API modification of the DTR line (asserting it) wasn't supported. I think python might have been silently failing.

I switched converters and it worked without issue (in serial-rs).

**Comment by dcuddeback** [comment]
@valarauca Glad to hear it!

**Comment by valarauca** [comment]
I'm starting to branch off the windows support in my own repo. The goal is that it will fetch driver configuration on open, and check configuration to warn of potential errors.

If it reaches maturity I'll submit a RFC/PR with the changes (and I'll test it on OSX/Linux, sorry about that with my last PR).
