### ISSUE TITLE
Add ARMv7 target

### ISSUE THREAD

**Issue by PAStheLoD** [dcuddeback/serial-rs#24]
Hello!

Is there any reason armv7 is not available as a target? Could you add it?

```
$ rustc -v --version
rustc 1.9.0-beta.2 (87cb73304 2016-05-04)
binary: rustc
commit-hash: 87cb733048f0072199b66bb3c0efe61d52623900
commit-date: 2016-05-04
host: armv7-unknown-linux-gnueabihf
release: 1.9.0-beta.2
```

Thanks!

**Comment by dcuddeback** [comment]
@PAStheLoD The only reason it wasn't included before is that arm7 wasn't a target triple for rustc when I wrote Cargo.toml and at the time Cargo didn't suport the `cfg()` syntax. Now that Rust 1.8 ships with a version of Cargo that supports `cfg()` syntax for specifying dependencies, I plan to bump the minimum supported version of Rust and adopt the `cfg()` syntax when I release v0.4 and then this won't be a problem going forward. In the mean time, I'll merge the PR from @RoPP to add arm7 as an explicit target.

**Comment by PAStheLoD** [comment]
Thanks for the detailed explanation!

**Comment by tylerwhall** [comment]
@dcuddeback I made a branch with the `cfg()` syntax for my own use since I'm using custom target triples. It would be convenient to have this in crates.io, though.
https://github.com/tylerwhall/serial-rs/commit/cf2cc6651ea0d8506b4fb10d21146303014ec6e1
