### ISSUE TITLE
Add a function to return all supported standard baud rates for the port

### ISSUE THREAD

**Issue by Susurrus** [dcuddeback/serial-rs#26]
This doesn't need to include non-standard baud rates, but it would be nice for when the user needs to select a baud rate from a list (like in a GUI dropdown) if there was a way to get a list of all standard supported rates for the platform as a vector that can be easily used to populate such a dropdown.

**Comment by dcuddeback** [comment]
I'm not aware of any API that returns supported baud rates for a serial port. That information usually comes from reading the hardware's datasheet, and then it's usually determined by a base clock frequency and a divisor with some simple formula for calculating the final baud rate. The best such an API could do is provide a guess as to what's commonly supported. This library has done that via the `BaudRate` enum.

**Comment by Susurrus** [comment]
I think you misunderstood what I meant. I'm not trying to have this library reach into the hardware driver and extract actual supported baud rates, I wanted to get a list of standard baud rates for the current platform. The baud rate enum is dependent on the platform as to what standard rates are supported, for all others you need to use BaudOther. It'd be very helpful to be able to easily get a list of those standard rates.
