### ISSUE TITLE
Add SerialPort::get_configuration()

### ISSUE THREAD

**Issue by Susurrus** [dcuddeback/serial-rs#31]
In lieu of #28 I'm creating this issue, since there's no way for me to reopen an issue. This is a suggestion to add the following function to the `SerialPort` trait:

``` rust
fn get_configuration(&self) -> PortSettings
```

I don't believe it should return a `Result` or `Option` as this should return the default configuration as soon as the port is created/opened and I can't imagine a scenario where as long as the `SerialPort` object exists, this could return a valid instance.

This is important to round out the possible round-tripping of settings. Right now `configure()` exists as a way to import settings but there's no way to export settings. This allows for copying configuration settings for a SerialPort to a new one (a use case I have in my serial terminal that supports changing ports).

**Comment by Susurrus** [comment]
Well, since PortSettings is unsized, this might not be the best function prototype. Maybe someone else can offer a better interface here?

**Comment by dcuddeback** [comment]
I'm not convinced that this method is necessary in an object-safe trait, which would be the only reason for adding it to `SerialPort`. It also doesn't seem necessary for the use case you mentioned. You can keep the user's desired settings outside of a SerialPort using the PortSettings struct and use that to configure new ports when switching.

**Comment by Susurrus** [comment]
I agree that's how I should do it. But it is a gap in the API that you can't read port settings in a similar fashion to how you write them.

**Comment by dcuddeback** [comment]
I'd rather wait until a real-life use case presents itself.
