### ISSUE TITLE
Document the use cases for SerialPort::configure() versus SerialPort::reconfigure()

### ISSUE THREAD

**Issue by Susurrus** [dcuddeback/serial-rs#32]
This also comes out of #28 since it split into a few different issues.

I'd like to suggest that the documentation make more clear the different between `configure()` and `reconfigure()` from the user's perspective. As a user of the serial library and looking at these functions and the documentation for them, I would think I'd want to use `configure()` for the initial configuration and `reconfigure()` for every configuration afterwards. But it's not clear that a) this is the recommended method and b) that this is the **required** way to use these. Especially since the example code only ever uses `reconfigure()`.

Maybe it makes more sense to remove `configure()` and create a second function `open_with_config()` that takes the port name and the desired initial configuration. And then `reconfigure()` is always used after initialization. I think that'd make the interface smaller and more clear. This would also compliment #31 by making opening new ports reusing existing port settings require 1 less function call.

**Comment by dcuddeback** [comment]
@Susurrus The documentation describes exactly what the methods do. The use cases are up to the user. Just use whichever is more convenient for your use case. [`examples/probe_pins.rs`](https://github.com/dcuddeback/serial-rs/blob/master/examples/probe_pins.rs) and [`examples/read_write.rs`](https://github.com/dcuddeback/serial-rs/blob/master/examples/read_write.rs) both use `configure()`, but it wouldn't hurt to add an example to the API documentation as well.

**Comment by mairsbw** [comment]
It described _what_ they do but not _why_ you'd use them. If they're equivalent, then there should be an additional comment like "This is identical to XX() and is provided here as an additional interface to configuring the serial port".

I'm looking at this as a new user, so it'll be very different than your perspective. If you're new to this library and you want to open and configure a serial port and you see both a `configure()` and a `reconfigure()` method, you'll likely draw similar conclusions to what I did. This is why it's so important to describe when these functions should be used and why, even if it's just to say they're equivalent functions and to use whichever is more convenient.

**Comment by Susurrus** [comment]
I'd also question why `reconfigure()` exists if all the examples use `configure()`. What was your reasoning for having two different configuration functions? Considering the extra maintenance and support burden of additional functions, and the confusion having two nearly-identical functions can cause, it seems prudent to reduce configuration to the single right way. It's part of the Python mentality that I think has made that language so easy to pick up and implement good code in and worth adopting elsewhere.
