### ISSUE TITLE
Permit numerical setting of baud rate

### ISSUE THREAD

**Issue by tkornack** [dcuddeback/serial-rs#38]
It would be welcome addition if all baud rates could be set with an integer via the BaudOther() type. Presently one must use Baud115200 instead of BaudOther(115200) but must use BaudOther(230400) instead of Baud230400. Is there a reason for this pattern?

**Comment by Susurrus** [comment]
See previous commentary on #10.

**Comment by dcuddeback** [comment]
@tkornack The `BaudRate` enum exposes which baud rates defined by termios and the Windows API (`B9600`, `B115200`, etc) are cross-platform. There is a constructor to create an instance of the enum from arbitrary integers if that's what you prefer.
