### ISSUE TITLE
Should use nix crate

### ISSUE THREAD

**Issue by ndusart** [dcuddeback/serial-rs#46]
I think this crate should use the [nix](https://github.com/nix-rust/nix) crate.
They already provide safe bindings to termios and ioctl and we should avoid to split the effort.

I'm trying to use your crate on an Android application and I think it should be more easy with the nix crate as they provide support for Android (it seems there is a bug now on android either in libc or in nix, but it should be fixed).

I hope you'll be open for discussing this point.

Thanks

**Comment by ndusart** [comment]
Some people may be interested that someone forked that crate to create [serialport](https://crates.io/crates/serialport) which use `nix` internally and supports then more platforms than this crate.

Moreover, it implements enumeration of serial devices.

**Comment by dcuddeback** [comment]
No, thank you. `nix` would add more dependencies for the same functionality, which is contrary to my goals.

If you're experiencing issues, please file a bug with some details. It's not clear from your description whether or not you're having issues with Android. I've not used Android myself, but I believe others have had success with it.

**Comment by ndusart** [comment]
@dcuddeback The problem is just that `termios-rs` use `#[cfg(target_os = "linux")]` which does not include android. So all definitions are missing.

I didn't say it's difficult to make it compile on Android, but we depends on you to make that move.
Android support was proposed to you (dcuddeback/termios-rs#7). Instead of proposing to test the compilation for going further, you just closed the discussion...

This issue was about resolving the real issue: the split of effort for binding an API for the most platforms possible. One implementation could already have added a platform while the other not, if you're depending on the wrong one, it's just a pity that we cannot all enjoy this work.

I do not blame your work, `nix` probably lacks some of your features also. I just don't understand the impossibility of talking here. `nix` has not a lot more dependencies than `termios-rs`, it mainly just depends on `libc` as your crate.

So, following your advice, here is the issue you probably want to read: there is no `::os::target` module for Android in `termios-rs`. But you probably do not give much interest into it.

Cheers.
