### ISSUE TITLE
OS independed PortSettings

### ISSUE THREAD

**Issue by luqasz** [dcuddeback/serial-rs#62]
Right now it is impossible to use `PortSettings` as a os independent settings.
```
trait `From<PortSettings>` is not implemented for `TTYSettings`
```
What I mean is to pass `PortSettings` to `write_settings()`

Can you please provide such ?

**Comment by dcuddeback** [comment]
@luqasz `PortSettings` can be passed to `configure()`.

**Comment by luqasz** [comment]
Ah right. Thx. Works.
