### ISSUE TITLE
Have a NativePort type

### ISSUE THREAD

**Issue by awelkie** [dcuddeback/serial-rs#7]
I'd like to create a struct that is just a wrapper over a serial port:

``` rust
use serial::SerialPort;
struct SomeStruct<S: SerialPort> {
    dev: S,
}
```

But in order to provide an `open` function, I'll have to duplicate the `cfg` logic that you already have:

``` rust
#[cfg(unix)]
impl SomeStruct<serial::posix::TTYPort> {
    pub fn open() -> Result<Self>;
}

#[cfg(windows)]
impl SomeStruct<serial::windows::COMPort> {
    pub fn open() -> Result<Self>;
}
```

It'd be nice if `serial` provided a type alias for the native implementation of `SerialDevice`, so that I could do something like this:

``` rust
use serial::NativeDevice;
impl SomeStruct<NativeDevice> {
    pub fn open() -> Result<Self>;
}
```

and it would work on all supported platforms.

**Comment by dcuddeback** [comment]
@awelkie I added a `SystemPort` type alias in v0.2.1.
